language: cpp

dist: bionic

compiler:
- gcc

os:
- linux

branches:
    only:
    - /.*/

notifications:
    email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install libboost-test-dev

script:
- autoreconf -f -i
- ./configure CXXFLAGS=--std=c++11
- make
- cd tests
- autoreconf -f -i
- ./configure CXXFLAGS=--std=c++11
- make
- ./coffio_test
- make check
